

public class Duck {
	int numberOfFriends;
	String favoriteFood;
	Duck(String favoriteFood, int numberOfFriends, String name) {
      	this.favoriteFood = favoriteFood;
      	this.numberOfFriends = numberOfFriends;
      	System.out.println("A new "+name+" duck is being generated by someone at the league.");
}
	void quack() {
		System.out.println("QUACK");
	}
	void waddle() {
		System.out.println("WADDLE WADDLE WADDLE");
	}
}
